# vim:fileencoding=utf-8:foldmethod=marker

# Theme
include themes/tokyo-night-moon.conf

# Font Size
font_size 12.0

# BEGIN_KITTY_FONTS
font_family      family="SauceCodePro Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# disable terminal bell
enable_audio_bell no

# enable remote control
allow_remote_control socket-only
listen_on unix:/tmp/kitty
